DROP SEQUENCE ACCOUNT_SEQ;
DROP SEQUENCE TASK_SEQ;
DROP SEQUENCE NOTIFICATION_SEQ;
DROP TABLE NOTIFICATION;
DROP TABLE TASK;
DROP TABLE ACCOUNT;

CREATE SEQUENCE ACCOUNT_SEQ
START WITH 1
MINVALUE 1
MAXVALUE 1000000
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TASK_SEQ
START WITH 1
MINVALUE 1
MAXVALUE 1000000
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE NOTIFICATION_SEQ
START WITH 1
MINVALUE 1
MAXVALUE 1000000
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE ACCOUNT (
  ID NUMBER(10) PRIMARY KEY,
  VK_KEY NUMBER(20) UNIQUE,
  TELEGRAM_KEY NUMBER(20) UNIQUE,
  LANGUAGE VARCHAR2(10),
  TIME_ZONE VARCHAR2(100)
);

CREATE TABLE TASK (
  ID NUMBER(10) PRIMARY KEY,
  TITLE VARCHAR2(60),
  BODY VARCHAR2(140) NOT NULL,
  ACCOUNT_ID NUMBER(10) NOT NULL REFERENCES ACCOUNT(ID),
  SERVER_DATE TIMESTAMP NOT NULL,
  SPECIFIED_TIME NUMBER(1) NOT NULL CHECK (SPECIFIED_TIME BETWEEN 0 and 1)
);

CREATE TABLE NOTIFICATION (
  ID NUMBER(10) PRIMARY KEY,
  SERVER_DATE TIMESTAMP NOT NULL,
  SPECIFIED_TIME NUMBER(1) NOT NULL CHECK (SPECIFIED_TIME BETWEEN 0 and 1),
  TASK_ID NUMBER(10) NOT NULL REFERENCES TASK(ID)
);